### ISSUE TITLE
Feature Request: Text Chat

### ISSUE THREAD

**Issue by cmar0ck** [rdegges/chatapp#2]
Would be pretty awesome if there was a text chat, too (for sharing links with chat partners, or if there is trouble with audio), is there a chance you could implement that?

**Comment by rdegges** [comment]
Should be pretty simple. The only thing you'd have to do is use websockets (maybe socket.io or pusher.com). If you want to keep it simple, using pusher.com is my favorite way as it makes it superrr simple.

I probably won't implement that on here as I wrote this as a small example app and am not using it all the time, but if anyone wants to send a PR to add functionality I'd love to merge it in!

**Comment by cmar0ck** [comment]
Implemented by myself now
