### ISSUE TITLE
sir i ue flask hw do i get the user authenticationto work with flask-user

### ISSUE THREAD

**Issue by rextech03** [rdegges/chatapp#5]
sir how do i make the auth.js work with flask upload than use okta. such that we can use the username in the link then the email

**Comment by rdegges** [comment]
You might want to check out the documentation for auth.js: https://github.com/okta/okta-auth-js

I'm not 100% able to understand your question, but you should be able to grab user information via auth.js, no problem.

**Comment by rextech03** [comment]
ok what i mean is I have an already working authentication system so I do not want to use okta. how do i use my own developed authentication system i built with flask or php
