### ISSUE TITLE
Tutoial request

### ISSUE THREAD

**Issue by rextech03** [rdegges/chatapp#7]
please am building a flask website and my school project needs me to complete it 2 weeks. Please can you make a tutorial on how you can use your script with flask. I would be happy am sure may other people would benefit from it. Please or at least help me out in my project Here is my email, markogujiuba@gmail.com. Thank because you how am stranded and need help please. Thank you.

**Comment by rdegges** [comment]
Sorry -- GItHub issues is not an appropriate place for this =(

**Comment by rextech03** [comment]
please where is the appropriate place

**Comment by rdegges** [comment]
You probably want to hire a developer to build an app for you, based on your request. You may want to try freelancer websites like odesk.com, etc.
